root_dir: "/home/helena/experiments_cataract/"
experiment_name: "cataract_v1.3_annotations_corrected"

model:
  name: simple
  num_classes: 12
  backbone:
    name: resnet50
    freeze: false

dataset:
  class_names: [
    "Capsule_polishing", "Hydrodissection",
    "Incision", "Irrigation_and_aspiration",
    "Lens_implant_settingup", "Others", "Phacoemulsification", "Rhexis",
    "Tonifying_and_antibiotics", "Viscous_agent_injection",
    "Viscous_agent_removal", "Wound_hydration"
  ]
  binary_phase: "Corneal_hydration"
  others_classes: ["Malyugin_ring_insertion", "Malyugin_ring_removal", "Suture", "Trypan_blue_injection"]
  train:
    params:
      root: "/home/helena/UCL_video_cataract/dataset_temporal/train/"
      max_side: 224
    loader_params:
      batch_size: 256
      shuffle: true
      num_workers: 16
      pin_memory: true
    transforms:
      flip:
        target: albumentations.HorizontalFlip
        params:
          p: 0.5
      brightness:
        target: albumentations.RandomBrightnessContrast
        params:
          brightness_limit: 0.2
          contrast_limit: 0.2
          p: 0.5
      jitter:
        target: albumentations.ColorJitter
        params:
          brightness: 0.2
          contrast: 0.2
          saturation: 0.2
          hue: 0.05
          p: 0.3

  val:
    params:
      root: "/home/helena/UCL_video_cataract/dataset_temporal/val/"
      max_side: 224
    loader_params:
      batch_size: 512
      shuffle: false
      num_workers: 16
      pin_memory: true

loss:
  target: losses.basic_loss.CataractLoss
  params:
    label_smoothing: 0.1

optimizer:
  target: torch.optim.AdamW
  params:
    lr: 1e-4        # tête de classification
    backbone_lr: 1e-5  # backbone pretrained

lr_scheduler:
  target: utils.lr_scheduler.get_linear_warmup_cosine_decay_lr_scheduler
  params:
    n_warmup_steps: 50
    n_total_steps: 26000  
    min_lr_ratio: 0.01    # le LR final sera 1e-4 * 0.01 = 1e-6

visualizer:
  row: 4
  col: 8
  num_batch_to_take: 2
  class_names: [
    "Capsule_polishing", "Hydrodissection",
    "Incision", "Irrigation_and_aspiration",
    "Lens_implant_settingup", "Others", "Phacoemulsification", "Rhexis",
    "Tonifying_and_antibiotics", "Viscous_agent_injection",
    "Viscous_agent_removal", "Wound_hydration"
  ]

metrics:
  others_classes: ["Others"]

train:
  epochs: 100
  device: "cuda:0"
  use_amp: true
  max_norm: 1.0
  log_every_n_steps: 10
  val_every_n_epoch: 1
  log_image_every_n_epoch: 1
  keep_ckpt: 3
